### ISSUE TITLE
Crash when compiling

### ISSUE THREAD

**Issue by sbrl** [weigert/proceduralweather#1]
Hey there! I found this through your blog post, which I found from a recent comment on r/proceduralgeneration on Reddit.

When try to compile this, I get the following error message:

```
g++ -std=c++11 territory.cpp -Wall -lSDL2 -I/usr/local/include -L/usr/local/lib -lnoise -lSDL2_image -lSDL2_ttf -o territory
In file included from view.h:4,
                 from territory.cpp:4:
worldgen.h:2:10: fatal error: noise/noise.h: No such file or directory
    2 | #include <noise/noise.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [makefile:7: all] Error 1
```

Reproduction steps:

```bash
git clone https://github.com/weigert/proceduralweather.git
cd proceduralweather/
make all
```

**Comment by weigert** [comment]
> Hey there! I found this through your blog post, which I found from a recent comment on r/proceduralgeneration on Reddit.

Awesome!

The compiler can't find the libnoise library. What operating system are you using?

Here is a similar issue on Ubuntu 19: https://github.com/weigert/territory/issues/15

libnoise is simply in a different location on some systems.

Let me know if doesn't work!

**Comment by sbrl** [comment]
Ah, I see. I thought that because of the `noise/noise.h`, it referred to a library local to the project, rather than system-wide.

I'm using Ubuntu 20.04, and I don't have `libnoise` (or `libnoise-dev`) installed - so that's probably the issue.
